   
alpdesk_frontendediting:
    path: /contao/alpdeskfee
    defaults:
        _controller: Alpdesk\AlpdeskFrontendediting\Controller\BackendController:endpoint
        _scope: backend
        _token_check: false
    methods: [POST]