services:

  _defaults:
    autoconfigure: true
    autowire: true

  alpdeskfrontendediting.eventservice:
    class: Alpdesk\AlpdeskFrontendediting\Events\AlpdeskFrontendeditingEventService
    arguments:
      - '@event_dispatcher'
    public: true
    
  Alpdesk\AlpdeskFrontendediting\Listener\HooksListener:
      arguments:
          - '@contao.security.token_checker'
          - '@alpdeskfrontendediting.eventservice'
      tags:
          - { name: contao.hook, hook: getPageLayout, method: onGetPageLayout, priority: 0 }
          - { name: contao.hook, hook: compileArticle, method: onCompileArticle, priority: 0 }
          - { name: contao.hook, hook: getContentElement, method: onGetContentElement, priority: 0 }
          - { name: contao.hook, hook: getFrontendModule, method: onGetFrontendModule, priority: 0 }
          
  Alpdesk\AlpdeskFrontendediting\Controller\BackendController:
      arguments:
          - '@contao.security.token_checker'
          - '@security.helper'
          - '@contao.csrf.token_manager'
          - '%contao.csrf_token_name%'
      tags:
          - controller.service_arguments
          
  Alpdesk\AlpdeskFrontendediting\Controller\AlpdeskbackendController:
      arguments:
          - '@twig'
      tags:
          - controller.service_arguments